### ISSUE TITLE
samsung n7102

### ISSUE THREAD

**Issue by m-snowman** [xaxaxa/n7102_kernel_lineage#1]
请问一下，可以利用这个来编译samsung n7102的安卓8版本吗？具体怎么使用

**Comment by m-snowman** [comment]
我不知道

**Comment by xaxaxa** [comment]
You can use this kernel with the n7100 version of lineageos (there is an unofficial release; it's android 7) on a n7102 phone; download the n7100 rom, extract boot.img, extract kernel and initrd from boot.img, replace kernel zImage with this kernel, re-pack boot.img, place into rom zip file, and flash it.
